spring:
  profiles:
    active: local
  mongodb:
    embedded:
      version: 4.0.21
---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      host: localhost
      port: 27017
      database: ${MONGO_DATABASE}
      authentication-database: admin
---
spring:
  config:
    activate:
      on-profile: nonprod
  data:
    mongodb:
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      host: localhost
      port: 27017
      database: ${MONGO_DATABASE}
      authentication-database: admin
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      host: localhost
      port: 27017
      database: ${MONGO_DATABASE}
      authentication-database: admin
---
logging:
  level:
    root: info